name: CI for Python Application
on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest
        export PYTHONPATH=src
        pytest --maxfail=1 --disable-warnings --junitxml=test-results/results.xml  # Run tests and output results to XML file
    - name: Create artifacts directory and file
      run: |
        mkdir -p artifacts
        touch artifacts/python_app.zip

    - name: List artifacts directory
      run: ls -la artifacts

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-application-artifact
        path: artifacts/*.zip
   # - name: Upload Artifact
    #  uses: actions/upload-artifact@v4
     # with:
      #  name: python-application-artifact
       # path: artifacts/*.zip
 
      
