name: CI for Python Application
on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest
        export PYTHONPATH=src
        pytest  --maxfail=1 --disable-warnings --junitxml=test-results/results.xml  # Run tests and output results to XML file

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-application-artifact
        path: artifacts/python_app.zip
  #  - name: Create directory for test results
   #   run: mkdir -p test-results
   

   # - name: Upload artifacts
   #   uses: astertom/nexus-upload-artifact@v1.1.0
    #  with:
      #  name: test-results
      #  path: test-results/results.xml  # Upload the test result file
      #  repositories: python-project/.github/workflows/
       #   # Specify the Nexus repository name
       # timeout: 60  # Timeout for upload
