name: CI for Python Application
on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create directory for test results
      run: mkdir -p test-results  # Create a directory to store the test results

    - name: Test with pytest
      run: |
        pip install pytest
        export PYTHONPATH=src
        pytest --maxfail=1 --disable-warnings --junitxml=test-results/results.xml  # Save the results in XML format

    - name: Upload test results as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results/results.xml  # Upload the test result file
